// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class GoogleTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;


  @Before
  public void setUp() {

    WebDriverManager.chromedriver().setup();

    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void googleTest() {


    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1024, 1000));
    driver.findElement(By.name("q")).sendKeys("Selenium");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("div:nth-child(2) > .rc .LC20lb")).click();
    driver.findElement(By.cssSelector("h2:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("h2:nth-child(1)")).getText(), is("What is Selenium?"));
//    driver.findElement(By.cssSelector(".bkWMgd:nth-child(2) .g:nth-child(1) .LC20lb")).click();
//    // 7 | click | css=.homepage |  |
//    driver.findElement(By.cssSelector(".homepage")).click();
//    // 8 | assertText | css=h2:nth-child(1) | What is Selenium? |
//    assertThat(driver.findElement(By.cssSelector("h2:nth-child(1)")).getText(), is("What is Selenium?"));
  }
}
